version: '3.5'

services:
  weather-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: weather-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-weather-api
    environment:
      - PORT=${PORT}
    env_file:
      .env
    ports:
      - '3000:3000'
    depends_on:
      - weather-db
    volumes:
      - ./src:/app/src
